### ISSUE TITLE
Not support gpu? 

### ISSUE THREAD

**Issue by Ikhwansong** [youchangxin/YOLOv4_tensorflow2#1]
hi, Thank for your sharing code.

I have a one question : Do not this code support gpu version by tensorflow?

**Comment by youchangxin** [comment]
It certainly supports TensorFlow GPU.

**Comment by Ikhwansong** [comment]
Because of absence of cudnn, cudatoolkit. it didn't work
I just have checked it and download cudnn&cudatoolkit by anaconda command then I could see it works!
Thanks
