### ISSUE TITLE
the loss is nan

### ISSUE THREAD

**Issue by zcdliuwei** [youchangxin/YOLOv4_tensorflow2#2]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/36565076/84239353-f2e28c00-ab2e-11ea-8d8f-dff8a3b2161a.png">

**Comment by youchangxin** [comment]
I will fix the Bug as soon as possible, I'm testing the new coed to save it .

**Comment by zcdliuwei** [comment]
I want to ask for your advice. I want to identify the bottles in the trash can. The real image is about this:

![20200611112928_B_Q](https://user-images.githubusercontent.com/36565076/85197584-8cbaed80-b314-11ea-9fb4-97bfe7a4325f.jpg)

![20200611112934_B_Q](https://user-images.githubusercontent.com/36565076/85197586-904e7480-b314-11ea-8233-4429f703a83a.jpg)

![20200611113139_B_Q](https://user-images.githubusercontent.com/36565076/85197588-90e70b00-b314-11ea-8998-6b84521aab70.jpg)

The most complex part of this scene is the dense shielding and stacking of bottles. Our purpose is to tell the customer who threw the bottle what kind of bottle he threw in, and it's better to return the location information of the bottle at the bottom of the trash can. At present, I use Yolo series for testing, and the effect is always unsatisfactory.

I want to know does you have any suggestions to improve the detection and classification ability in this scenario?

Much obliged for your assistance.

**Comment by msergenergen** [comment]
Hi, 
Firstly, thanks for your repo creation. Did you fix this bug? I still get nan, you can see output following output.

> =>EPOCH   0  STEP  241   lr: 0.000068   ciou_loss: 9.67   conf_loss: 11385.40   prob_loss: 84.94   total_loss: 11480.01
> =>EPOCH   0  STEP  242   lr: 0.000068   ciou_loss: 1.82   conf_loss: 11522.95   prob_loss: 16.12   total_loss: 11540.89
> =>EPOCH   0  STEP  243   lr: 0.000069   ciou_loss: 3.79   conf_loss: 11352.79   prob_loss: 33.10   total_loss: 11389.68
> =>EPOCH   0  STEP  244   lr: 0.000069   ciou_loss: 1.77   conf_loss: 11479.06   prob_loss: 17.01   total_loss: 11497.84
> =>EPOCH   0  STEP  245   lr: 0.000069   ciou_loss: 1.86   conf_loss: 11647.79   prob_loss: 15.82   total_loss: 11665.48
> =>EPOCH   0  STEP  246   lr: 0.000069   ciou_loss: 1.88   conf_loss: 11362.14   prob_loss: 16.45   total_loss: 11380.47
> =>EPOCH   0  STEP  247   lr: 0.000070   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  248   lr: 0.000070   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  249   lr: 0.000070   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  250   lr: 0.000071   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  251   lr: 0.000071   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  252   lr: 0.000071   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
> =>EPOCH   0  STEP  253   lr: 0.000071   ciou_loss:  nan   conf_loss:  nan   prob_loss:  nan   total_loss:  nan
